version: '3'
services:
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '80:80'
  backend:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    environment:
      - NODE_ENV=production
      - MONGO_URI=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
